        "White_Pen","Silver_Pen","Leo_Pen","Sublimation_Pen","Sanitizer_Pen","White_Mug"," Magic_Mug","Color_Mug"," Silver_Mug","Golden_Mug","
        Thermos_Mug","Sport_Mug_300ml","Travel_Mug_600ml","Mirror_Silver_Mug ","Mirror_Golden_Mug","Black_Frame_Mug","V_Shape_Mug","Enamel_Mug","Mason_jar_Mug","Copper_Mug","
        Sublimation_Metal_Key_Chain","MDF_Key_Chain_1_Side","MDF_Key_Chain_2_Side","Key_Chain_Metal_1_Side","Binding_Machine","  Mug_Machine","Lamination_Machine_A3","Heat_Press_Machine_38_A3"," Portable_Heat_Press_Machine","Five_in_one_Heat_Press","
        Mug_Machine_Five_in_one","Flash_Stamp_Machine","Pen_Machine","Id_Cutter","Cap_Machine","Desk_Mate_Stamp","Epson_Printer_Machine_L382","Epson_Printer_Machine_L805"," Transfer_Paper_Light","Transfer_Paper_Dark","
        Certificate"," Special_Paper","ATM_Flash_8GB","ATM_Flash_32GB","Mouse_Pad_3mm","Mouse_Pad_2mm","Cup_Coaster"," MDF_1_Side_Board","MDF_2_Side_Board","Photo_Album","
        Frame","Door_Hanger_1_Side","Door_Hanger_2_Side"," Glove_Pair","Sublimation_ink_1L","Tape_Plaster"," Cap","One_Side_Menu","Six_Side_Menu","Three_Side_Menu","
        Flag_Table_Stand"," Shopping_Bag","Roll_Up","Table_Stapler"," Executive_Agenda","Lamination_Mate","lamination_Glossy","Business_Card_Holder","Sublimation_Paper","Heat_Press_Machine_40_60","
        Plotter_70cm","Plotter_130cm"," Lamination_Machine_A2","Eight_in_1_Heat_Press","Two_in_1_Heat_Press"," Stamp_HB_42","Stamp_20_40"," Stamp_Hy_42_Top_Ink","Clear_Mason_Jar_Mug","kids_Mug","
        Bamboo_Frame_15_10"," Bamboo_Frame_17_17","Bamboo_Aluminium_Sheet_15_25","Silcon_Pad_38_38","Silcon_Pad_40_60","Mug_Box"," Stamp_Rubber","Mold_11_oz_Long","Mold_11_oz_Short","Mold_9_oz","
        Mold_6_oz","MDF_Wine_Box","Art_Knife","Name_Tag","Stamp_20_50","Stamp_30_60"," Crystal_Stamp","Mold_V_Shaped","T_Shirt_Guide","Vinly_Tool","Tagging_Gun","Tag_Pin"
